name: Publish to GitHub Container Registry

on:
  # trigger manual workflow
  workflow_dispatch:
  # trigger workflow on push to master when changes happen in one folder
  push:
    tags:
      - "*"
  
jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish and push the container image
        run: |
          dotnet publish Enliven/Enliven.csproj --os linux --arch x64 -c Release /p:PublishProfile=DefaultContainer /p:ContainerRepository="enlivenbot/enliven" /p:ContainerRegistry="ghcr.io"
